import { asset } from "./assets";
import type { ChatItem, DetailTab, ExploreItem, Playbook, SettingsTab } from "./types";

export const playbooks: Playbook[] = [
  {
    title: "Investor Roundtable",
    subtitle: "Ten legendary investors debate any stock - live verdict",
    avatar: asset("assets/figma/sidebar-playbook-1.png"),
    cover: asset("assets/covers/cover-roundtable.webp"),
    tag: "Debate",
    stat: "2.6K",
  },
  {
    title: "LAB Short War Room",
    subtitle: "Live short-seller console for LABUSDT - squeeze risk",
    avatar: asset("assets/figma/sidebar-playbook-2.png"),
    cover: asset("assets/covers/cover-lab.webp"),
    tag: "Crypto",
    stat: "1.8K",
  },
  {
    title: "Citrini Operating System",
    subtitle: "Six modules - live macro indicators + megatrend tracker",
    avatar: asset("assets/figma/sidebar-playbook-3.png"),
    cover: asset("assets/covers/cover-citrini.webp"),
    tag: "Macro",
    stat: "9.1K",
  },
  {
    title: "Theme Tracker - Humanoid Robots",
    subtitle: "75 names across 9 supply-chain layers, scored daily",
    avatar: asset("assets/figma/sidebar-playbook-4.png"),
    cover: asset("assets/covers/cover-btcprice.webp"),
    tag: "Theme",
    stat: "3.2K",
  },
  {
    title: "BTC Bet Scanner",
    subtitle: "Polymarket BTC daily-close - 4-way probability blend",
    avatar: asset("assets/figma/sidebar-playbook-5.png"),
    cover: asset("assets/covers/cover-btcbet.webp"),
    tag: "Polymarket",
    stat: "5.7K",
  },
];

export const chats: ChatItem[] = [
  { title: "Crypto Price + AI Trend Pulse", time: "2 min ago" },
  { title: "$AVGO earnings recap", time: "26 min ago" },
  { title: "Macro & rates this week", time: "1 hour ago" },
  { title: "Semis vs power-grid rotation", time: "4 hours ago" },
  { title: "NVDA options flow check", time: "Yesterday" },
  { title: "AI infra shipment watch", time: "Tue" },
  { title: "FOMC liquidity map", time: "Mon" },
];

export const exploreItems: ExploreItem[] = [
  {
    title: "Serenity Tweet Tracker",
    desc: "Backtest of @aleabitoreddit's tweet signals. Tweet signals refresh hourly; full analytics refresh daily.",
    author: "Alva_FinTwit_Tracker",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2059106872170352640.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-5db5bf94-b0e6-44ab-8b47-ab858660193f_cronjob.webp",
    price: "$50",
    remixes: "6",
    views: "12.8K",
  },
  {
    title: "Investor Roundtable",
    desc: "Pick any stock and convene a roundtable of ten legendary investors, framework analysts, and a Portfolio Manager.",
    author: "Mickie",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2059844209485787136.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-2df592a4-afe6-475c-914f-72d5ea8b1ced_cronjob.webp",
    remixes: "1",
    views: "817",
  },
  {
    title: "LAB Short War Room",
    desc: "Live short-seller console for the LABUSDT Binance perp: price, squeeze risk, funding cost, positioning, and KOL radar.",
    author: "Algostonk",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2059856512545390592.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-7be59a45-f647-4803-8e8f-9b7b18a0bdc8_cronjob.webp",
    remixes: "1",
    views: "23.6K",
  },
  {
    title: "PURR mNAV Tracker",
    desc: "Live tracker of Hyperliquid Strategies Inc market cap vs HYPE token NAV with hourly snapshots and daily AI digest.",
    author: "harryz",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2064708202913931264.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-1d3c9cc4-0a5e-4215-bf34-962a21f52fc7_release.webp",
    price: "$5/mo",
    remixes: "0",
    views: "363",
  },
  {
    title: "LAB Unlock Put War Room",
    desc: "Live LAB short war room with unlock-risk tracking, short PnL, and deep OTM Aug 21 $1 put jump-risk pricing.",
    author: "Aks_V",
    avatar: "https://pbs.twimg.com/profile_images/1790813661734277120/ovg3uu67_normal.jpg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-d4ea559a-1853-4588-b563-d1e4c19102ad_cronjob.webp",
    remixes: "0",
    views: "322",
  },
  {
    title: "FinTwit Alpha Leaderboard",
    desc: "Rank public FinTwit creators by simulated signal performance and search the covered creator playbooks.",
    author: "Alva_FinTwit_Tracker",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2059106872170352640.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/Leaderboard_6143a899-1ddc-4719-b662-49f74e73a71c.png",
    remixes: "11",
    views: "7.4K",
  },
  {
    title: "US Earnings Calendar",
    desc: "Live S&P 500 earnings calendar with a 7-signal pre-earnings setup scorer.",
    author: "Mickie",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2059844209485787136.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-15efd59a-f07e-410f-a94b-99fe9823c253_cronjob.webp",
    remixes: "0",
    views: "138",
  },
  {
    title: "Gamma Squeeze CentCom",
    desc: "Options risk console tracking squeeze conditions across SPY, QQQ, and single-name momentum setups.",
    author: "decenfund",
    avatar: "https://lh3.googleusercontent.com/a/ACg8ocJUWSM5nTFTe9dj9ssYINop95N0zQuYa_NFErC3oAYP0SK3p9o=s96-c",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-f0d07792-ea4b-4712-a6d2-24792e663c9c_cronjob.webp",
    remixes: "1",
    views: "111",
  },
  {
    title: "Portfolio Watch Automation Spec",
    desc: "Detailed runbook for IBKR portfolio watch automation, anomaly attribution agents, prompts, and persisted audit outputs.",
    author: "harryz",
    avatar: "https://alva-ai-static.b-cdn.net/prd/avatar/2064708202913931264.jpeg",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-735a7ece-2991-476e-97b6-3bacc2ab4eff_release.webp",
    remixes: "0",
    views: "39",
  },
  {
    title: "SALP Thesis Tracker",
    desc: "Tracks Situational Awareness LP: long Power + AI Cloud + SNDK, short SMH ETF and mega-cap semis.",
    author: "alvin0617",
    avatar: "https://lh3.googleusercontent.com/a/ACg8ocKCdCZHv4wDOFdD3tYMbJ2BCJVUEsPtrQwqTR4uDFRS44lWaw=s96-c",
    cover: "https://alva-ai-static.b-cdn.net/thumbnails/screenshot-4c11a81f-4a00-406a-94be-0de208ed07d8_cronjob.webp",
    remixes: "1",
    views: "19.8K",
  },
];

export const settingsTabs: Array<{ id: SettingsTab; label: string }> = [
  { id: "account", label: "Account" },
  { id: "usage", label: "Usage" },
  { id: "portfolio", label: "Portfolio" },
  { id: "alvaAgent", label: "Alva Agent" },
  { id: "alerts", label: "Automations" },
  { id: "apiKey", label: "API Key" },
];

export const detailTabs: Array<{ id: DetailTab; label: string }> = [
  { id: "overview", label: "Overview" },
  { id: "analytics", label: "Analytics" },
  { id: "strategy", label: "Strategy" },
  { id: "feed", label: "Feed" },
];
